name: Deploy Pipeline

on:
    push: 
        branches: [main]
    workflow_dispatch:

env:
    AWS_REGION: us-east-1
    TF_VAR_notification_email: ${{ secrets.TF_VAR_notification_email }}

jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with: 
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
                  aws-region: ${{ env.AWS_REGION }} 

            - name: Setup Python
              uses: actions/setup-python@v4
              with: 
                  python-version: '3.11'

            - name: Package Lambda data_processor
              run: |
                  cd lambda/data_processor
                  pip install -r requirements.txt -t .
                  zip -r ../data_processor.zip .

            - name: Package Lambda report_generator
              run: |
                  cd lambda/report_generator
                  pip install -r requirements.txt -t .
                  zip -r ../report_generator.zip .
                
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v2
              with: 
                  terraform_version: 1.6.0
                  terraform_wrapper: false


            - name: terrafrom init
              run: |
                  cd terraform
                  terraform init

            - name: terraform plan
              run: |
                  cd terraform 
                  terraform plan
                
                
            - name: terraform apply
              run: |
                  cd terraform 
                  terraform apply -auto-approve

            - name: Show Terraform Outputs
              run: |
                  cd terraform
                  terraform output

            - name: Get Terraform Outputs
              run: |
                  cd terraform
                  INPUT_BUCKET=$(terraform output -raw input_bucket)
                  PROCESSED_BUCKET=$(terraform output -raw processed_bucket)

                  echo "INPUT_BUCKET=$INPUT_BUCKET" >> $GITHUB_ENV
                  echo "PROCESSED_BUCKET=$PROCESSED_BUCKET" >> $GITHUB_ENV
            
            - name: Upload test file to S3
              run: |
                  aws s3 cp sample_data/csv_test_events.csv s3://$INPUT_BUCKET/

            - name: Wait for processing
              run: |
                  echo "Waiting 10 seconds for processing..."
                  sleep 15
            
            - name: Check processed files in output S3
              run: |
                  echo "Checking for processed files in S3..."
                  TODAY=$(date +%Y-%m-%d)
                  aws s3 ls s3://$PROCESSED_BUCKET/processed-data/$TODAY/